trigger:
  batch: true
  branches:
    include:
      - "master"
  
variables:
- name: SolutionBaseName
  value: 'SFA.DAS.EmployerIncentives'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/3.0.14
    endpoint: SkillsFundingAgency

pool:
  name: DAS - Continuous Integration Agents
  demands: LATEST_DOTNET_VERSION -equals 3.1

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)